[package]
name = "aqi-alert-bot"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serenity = "0.11"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }