FROM rust:1.72.1 as build

COPY src/ /build
COPY Cargo.toml /build/Cargo.toml
COPY Cargo.lock /build/Cargo.lock

WORKDIR /build
RUN cargo build --release

FROM scratch

WORKDIR /app
COPY --from=build /build/target/release/aqi-alert-bot .

CMD ["aqi-alert-bot"]