name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  image_name: mpuckett259/aqi-alert-bot

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ github.sha }}